# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
permalink:     '/blog/:year/:title/'
#relative_permalinks: false

# Setup
title:               Siddharth Bhal
tagline:             'MS student at Virginia Tech'
description:         'A masters student in Computer Engineering Dept of Virginia Tech. Spends time reading about IOT, Linux Kernel, Swimming.'
url:                 http://sbhal.com
baseurl:             http://sbhal.com
paginate:            4

# About/contact
author:
  name:              Siddharth Bhal
  url:               https://sbhal.com
  email:             siddharth0bhal@gmail.com
  gravatar_md5:      174a9d47e67300db8dc67d2844980b7c
  github:	     sbhal
  linkedin:          siddharthbhal
  twitter:           keenbhal
  disqus_shortname:  sbhal
  google_analytics_id: UA-26469328-1


# Custom vars
version:             1.0.0

# Required Gems
gems: [jekyll-paginate, jekyll-gist]
